name: ci
on:
  push:
    branches:
      - master
      - develop
      - feat/dev-245-build-binaries
    tags:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        python:
          - 3.5
          - 3.6
          - 3.7
    env:
      GDC_CLIENT_ZIP: "gdc-client.zip"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Run Tests
      if: matrix.os != 'windows-latest'
      run: |
        python -m pip install --upgrade pip
        pip install tox
        tox -e py
    - name: Package
      run: |
        cd bin
        pip install virtualenv
        . ./package
        echo ::set-env name=GDC_CLIENT_ZIP::$GDC_CLIENT_ZIP
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        name: py${{ matrix.python }}-${{ env.GDC_CLIENT_ZIP }}
        path: bin/gdc-client_*.zip
